name: Dog-Cows
favicon: null
layout_spectrum: 0.2569759
typography_spectrum: 0.9255471
title: Apple System Engineers at Large
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#848483'
    - '#515150'
    - '#323231'
    - '#aeaead'
  brandStrength: 0.6875
  lightness: 0.966146
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
