typography_spectrum: 0.9255471
color:
  brandColors:
    - '#000000'
    - '#848483'
    - '#515150'
    - '#323231'
    - '#aeaead'
  brandStrength: 0.6875
  lightness: 0.966146
  saturation: 0.5625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2569759
analytics:
  google: null
  facebook: null
  twitter: null
name: Dog-Cows
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Managing macOS
description: Things should just work.
purpose: []
